[versions]
minecraft = "1.20.2"
parchment_minecraft = "1.20.1"
parchment_mappings = "2023.09.03"

fabric_loader = "0.14.24"
fabric_api = "0.89.3+1.20.2"

neoforge = "20.2.4-beta"
neogradle = "7.0.5"

jetbrains_annotations = "24.0.1"
autoservice = "1.1.1"
pngj = "2.1.0"

mixinextras = "0.2.0"

mdg_dsl = "1.5.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }
pngj = { module = "ar.com.hjg:pngj", version.ref = "pngj" }

mixinextras_fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }
mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.4.4" }
neogradle_userdev = {id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
neogradle_mixin = {id = "net.neoforged.gradle.mixin", version.ref = "neogradle" }
#librarian = {id = "org.parchmentmc.librarian.forgegradle", version = "1.2.0"}
mdg_plugin = {id = "org.groovymc.modsdotgroovy", version = "1.4.3"}
curseforgegradle = {id = "net.darkhax.curseforgegradle", version = "1.1.16"}
minotaur = {id = "com.modrinth.minotaur", version = "2.8.1"}
